name: Python Lint

on: 
  push:
    paths:
      - 'src/backend/**'
  pull_request:
    paths:
      - 'src/backend/**'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: psf/black@stable
        with:
          src: 'src/backend/'
